"""empty message

Revision ID: c8a8517523d7
Revises: 
Create Date: 2019-12-05 14:17:56.166261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8a8517523d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hastags')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hastags',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_user_id'], ['users.id'], name='hastags_created_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='hastags_pkey')
    )
    # ### end Alembic commands ###
